CONSTRUCTION INSTRUCTIONS FOR A KOSSEL
======================================
Printer: http://reprap.org/wiki/Kossel, designed by Johann Rocholl
Document Author: gblock@ctoforaday.com


From notes taken during the build itself, and referenced against replibot.blogspot.co.uk and http://www.flickr.com/photos/jcrocholl
These instructions ARE INCOMPLETE.  I've not even finished the build yet.  Your mileage will vary.  This will be wrong on more than one occasion, and you will throw good money away on something that you'll have to change tomorrow.

I'm steering religiously close to the Kossel design; this document will change as Johann's underlying design does.


Bill of Materials:  Printed Parts
---------------------------------

1 x effector.stl
6 x frame_cheek.stl
6 x frame_endstop.stl
6 x frame_motor.stl
3 x frame_top.stl
3 x roller_left.stl
3 x roller_right.stl
3 x round_glass.stl
1 x tensioner_axle.stl
3 x tensioner_608.stl
3 x spool.stl

BEFORE PRINTING: 

1. Make adjustments for the size of your round base.
   At the time of writing, adjust the round_glass.stl to match the size of your round base; I believe this is moving to configuration.scad.

2. Make adjustments for the bearings you've chosen.
   We're splurging on posh bearings with delrin cases from igus; you can follow Kossel's lead and heat-shrink yourself some tires on ordinary bearings if that's the way you want to play it; but change configuration.scad to match your bearings.


PRINTING:

The accuracy of the system depends on a good spool.  I had really beautiful ones printed by iMaterialize's high-resolution printing process; you can use anything you like, so long as it's well made.  Don't use a sloppy spool.

AFTER PRINTING: Get all your shit together in one place.


Bill of Materials:  Tools
1 x 2.5mm hex driver (I use hex nuts for everything, they're purty)
1 x 5.5mm nut driver (Ditto)

Bill of Materials: Exoskeleton


Bill of Materials: Brains
-------------------------

1 x Total cheat by buying a completed brain that supports a...
1 x 24v power supply.






BUILD THE EXOSKELETON
---------------------

STEP 1:  Attach round_glass.stl sections to hold the print area.

3 x 'short' OpenBeam
3 x round_glass.stl
6 x M3 nuts
3 x M3x8mm screws (? Can't verify - I have a 10" plate and a bastardized setup.)

First you're going to need to do the one thing you'd prefer to do last - attach the sections that will hold your print base.  This is because the nuts will be trapped in the center of the upper horizontal section, and you'll be capping both ends of the extrusion in the next step when you build the exoskeleton.

Best to just get it over with.  Choose three of the short segments of OpenBeam that will be the upper section of the lower support, and attach your round_glass.stl sections in the center.  You can get the positioning right later - what's important now is that they're there, and facing the correct position (on the upper side, pointing what will be towards the center of the platform).


STEP 2:  Build 3 (three) 'sidewalls'; for each:
1 x 'short' OpenBeam with a round_glass.stl attached.
1 x 'short' OpenBeam
2 x frame_motor.stl
8 x M3x8mm screws
8 x M3 nuts

Pair the frame motors with the sidewalls; the angled bit will overhang on either side of the sidewall, and the protruding bit will be on the inside (and will eventually hold the motor, at an angle that points the motor's rotor towards the corner.)  Your round_glass.stl should be at the 'top' of the unit, pointing in the same direction as the motor mount.


STEP 3: Attach corners and vertical posts to the sidewalls:
3 x sidewalls, created moments ago;
3 x 'long' OpenBeam
6 x corner.stl
12 x M3x20mm screws
12 x M3 nuts

At each corner, connect two of the sidewalls by passing an M3x8mm bolt through the corner, through the 'wing' of the frame.stl, and into the OpenBeam extension; each vertical post gets two screws in each of the two outer faces.

This is most easily done by loosely threading a nut onto the end of the bolt and 'sliding' the vertical rail down the nuts into the unit, tightening from the outside once that position is locked.

At this time, your round_glass.stl extensions should be all at the top of the triangle, and all pointing inwards; it should be obvious where your glass is going to be mounted.


TODO(gblock): Attach tensioners (there are three):


TODO(gblock): Build an upper corner (there are three):


TODO(gblock): Attach motors and spool.


TODO(gblock): Run the filament and apply tension.



ATTACH THE ROLLERS TO THE BEAMS
-------------------------------
To build a roller (there are three):
1 x roller_left.stl
1 x roller_right.stl
6 x 623 bearings
4 x M3x30mm screws (to hold left and right together)
6 x M3x8mm screws (to pin the delrin rollers, three in each half)
10 x M3 nuts

Attach the rollers to left and right halves, and then pin the left and right halves to the frame motor.
Note that in my print, the left and right halves came out _just_on the edge of what a 30mm will hold.

Each half has an extension that sticks out; orient that so that the sticky-outy-bit is on the top of the roller, and facing inwards into the triangle; this is where you'll attach the effector later.


BUILD YOUR EFFECTOR
-------------------
1 x finished extruder of your choice + bolts/screws to screw to effector.
1 x effector.stl
6 x (where the fuck did I get these awesome arms from?)
6 x M3x8mm screws
6 x M3 nuts

The effector platform gets the extruder bolted to it centrally, top or bottom, it's your choice; most people appear to be putting it above, to leave more vertical room for the build space, but that can result in the delta arms hitting the extruder (which then affects the horizontal size of the build space).  Your decision will ultimately be based on how big (or how small) your extruder is.

CENTER IT CAREFULLY.  Deltas are geometry-based, and the geometry *MUST* be good; your extruder should sit exactly within the center of the effector.  Arms must be precisely the same length - again, geometry *MUST* be perfect, or it will affect your print.


ATTACH YOUR EFFECTOR TO THE ROLLERS
-----------------------------------
6 x M3x12mm screws
6 x M3x6mm nuts

Attach each arm to the outside of the roller.


TODO(gblock): Attach endstops
TODO(gblock): Wire all this shit together
TODO(gblock): ...
TODO(gblock): ...
TODO(gblock): profit.



Parts suppliers (+prices?) used:
TriDPrinting.com
McMaster-carr
SeeMeCNC
Farnell/Element14
MatterHackers
Panucatt
TrinityLabs
iMaterialize
OpenBeamUSA
igus.co.uk


Bearings
------------------
BB-623-B180-10-ES bearings, delrin rollers, igus.co.uk - Stupidly priced.
